server:
  port: 5050

spring:
  application:
    name: weasley
  jpa:
    # Show Console SQL Query
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        jdbc.lob.non_contextual_creation: true
        jdbc.time_zone: UTC
        id.new_generator_mappings: true
    generate-ddl: true
    open-in-view: true

logging:
  level:
    org:
      hibernate.type.descriptor.sql.BasicBinder: TRACE

google:
  jwkUrl: https://www.googleapis.com/oauth2/v3/certs

jwt:
  key: test1231321
